/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoWaitlistFormRouteImport } from './routes/demo.waitlist-form'
import { Route as DemoFormRouteImport } from './routes/demo.form'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWaitlistFormRoute = DemoWaitlistFormRouteImport.update({
  id: '/demo/waitlist-form',
  path: '/demo/waitlist-form',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo/form',
  path: '/demo/form',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/waitlist-form': typeof DemoWaitlistFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/waitlist-form': typeof DemoWaitlistFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/waitlist-form': typeof DemoWaitlistFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/form' | '/demo/waitlist-form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/form' | '/demo/waitlist-form'
  id: '__root__' | '/' | '/demo/form' | '/demo/waitlist-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoFormRoute: typeof DemoFormRoute
  DemoWaitlistFormRoute: typeof DemoWaitlistFormRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/waitlist-form': {
      id: '/demo/waitlist-form'
      path: '/demo/waitlist-form'
      fullPath: '/demo/waitlist-form'
      preLoaderRoute: typeof DemoWaitlistFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/demo/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoFormRoute: DemoFormRoute,
  DemoWaitlistFormRoute: DemoWaitlistFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
